Rework the test system

diff --git a/test/bin/make-command-test b/test/bin/make-command-test
--- a/test/bin/make-command-test
+++ b/test/bin/make-command-test
@@ -15,18 +15,24 @@ main() {
 }
 
 assert-env() {
+  # TEST_DIR="$PWD/foo"
   TEST_DIR="$PWD/test/commands"
+
   TEST_BIN="$PWD/test/bin"
   TEST_LIB="$PWD/test/lib"
+
   export GIT_HUB_CONFIG="$PWD/test/githubconfig"
-  export GIT_HUB_LIST_SIZE=10
-  export PATH=$TEST_BIN:$PATH
-  # export GIT_HUB_TEST_COMMAND=1
+  export PATH=$TEST_BIN:$TEST_LIB:$PATH
+
+  export GIT_HUB_TEST_MAKE=true
+  export GIT_HUB_TEST_INTERACTIVE=true
   export GIT_HUB_TEST_COLS=80
   export GIT_HUB_TEST_LINES=24
 
   [ -z "$GIT_DIR" ] && die "GIT_DIR must be set"
-  [[ $GIT_DIR =~ test/repo/(git-hub|perlball|not-repo)/?$ ]] ||
+  [[ $GIT_DIR =~ test/repo/[-_a-zA-Z0-9]+/?$ ]] ||
+    die 'Invalid value for $GIT_DIR'
+  [[ -d $GIT_DIR ]] ||
     die 'Invalid value for $GIT_DIR'
   GIT_DIR_DIR="${GIT_DIR%/}"
   GIT_DIR_DIR="${GIT_DIR_DIR/*\//}"
