remove old test and add ability to make new tests

diff --git a/test/commands/make-test-case b/test/commands/make-test-case
--- a/test/commands/make-test-case
+++ b/test/commands/make-test-case
@@ -1,5 +1,59 @@
 #!/bin/bash
 
-export GIT_HUB_TMP=$PWD/tmp
+set -e
 
-"$@"
+TEST_DIR="$PWD/test/commands"
+
+main() {
+    assert-env "$@"
+    make-command "$@"
+    make-test-case-dir
+    make-run-bash
+    run-command
+    clean-json
+
+    echo "Created '$TEST_CASE_PATH'"
+}
+
+assert-env() {
+    export PATH=$TEST_DIR:$PATH
+    [ -z "$GIT_DIR" ] && die "GIT_DIR must be set"
+    [[ $GIT_DIR =~ ^(git-hub|perlball|not-repo)$ ]] ||
+        die 'Invalid value for $GIT_DIR'
+    :
+}
+
+make-command() {
+    TEST_CASE_CMD="$@"
+}
+
+make-test-case-dir() {
+    test_dir="$TEST_DIR/${test_dir// /_}"
+    TEST_CASE_DIR="${GIT_DIR}:${TEST_CASE_CMD// /_}"
+    TEST_CASE_PATH="$TEST_DIR/$TEST_CASE_DIR"
+    mkdir -p "$TEST_CASE_PATH"
+}
+
+make-run-bash() {
+    cat <<... > $TEST_CASE_PATH/run.bash
+export GIT_DIR=\$TEST_DIR/../repo/$GIT_DIR
+$TEST_CASE_CMD
+...
+}
+
+run-command() {
+    export GIT_HUB_HEADER="$TEST_CASE_PATH/api-head"
+    export GIT_HUB_OUTPUT="$TEST_CASE_PATH/api-out"
+    export GIT_HUB_ERROR="$TEST_CASE_PATH/api-err"
+    $TEST_CASE_CMD > "$TEST_CASE_PATH/stdout" 2> "$TEST_CASE_PATH/stderr"
+}
+
+clean-json() {
+    if [ -s "$TEST_CASE_PATH/api-out" ]; then
+        $TEST_DIR/clean-json.rb $TEST_CASE_PATH/api-out
+    fi
+}
+
+die() { echo "$@" >&2; exit 1; }
+
+main "$@"
